"""Map ROS package.xml files in a workspace onto a ros-kilted Conan require."""

from __future__ import annotations

import json
from dataclasses import dataclass, field
from pathlib import Path
from xml.etree import ElementTree as ET

DEPEND_TAGS = {
    "depend",
    "build_depend",
    "build_export_depend",
    "exec_depend",
    "buildtool_depend",
    "buildtool_export_depend",
}

SKIP_DIR_NAMES = {"build", "install", "log", ".git", ".svn", "__pycache__"}
VARIANT_ORDER = ("core", "base", "desktop")
DEFAULT_GENERATORS = ("CMakeToolchain", "CMakeDeps", "VCVars", "ROSEnv")
GENERATED_HEADER = "# Generated by `conan ros:init` from package.xml. Do not edit by hand."


def ros_profile_overlay_path() -> Path:
    return Path(__file__).resolve().parent / "data" / "ros.profile"


def compose_ros_profiles(
    profile_host,
    profile_build,
    overlay=None,
    default_host="default",
    default_build="default",
):
    """Append the ROS overlay after the user (or default) profiles. Last profile wins."""
    overlay = str(Path(overlay) if overlay else ros_profile_overlay_path())

    def _compose(existing, default):
        items = [str(p) for p in existing] if existing else [default]
        if overlay not in items:
            items.append(overlay)
        return items

    return _compose(profile_host, default_host), _compose(profile_build, default_build)


def add_mapping_args(parser):
    parser.add_argument(
        "path",
        nargs="?",
        default=".",
        help="Workspace root to scan for package.xml (default: current directory)",
    )
    parser.add_argument(
        "--distro",
        default="kilted",
        help="ROS distro catalog to use (default: kilted)",
    )
    parser.add_argument(
        "--requires",
        default=None,
        help="Conan reference to require (default: ros-<distro>/<catalog version>)",
    )
    parser.add_argument(
        "--variant",
        choices=list(VARIANT_ORDER),
        default=None,
        help="ros-kilted variant override. Default: smallest variant that covers all deps.",
    )
    parser.add_argument(
        "--dry-run",
        action="store_true",
        help="Print the mapping without writing conanfile.txt",
    )


def mapping_from_args(args):
    return map_workspace(
        Path(args.path),
        distro=args.distro,
        requires=args.requires,
        variant=args.variant,
    )


class RosConsumerError(Exception):
    """User-facing mapping or workspace error."""


def _local_tag(tag: str) -> str:
    return tag.split("}", 1)[-1]


def _text(node: ET.Element | None) -> str:
    if node is None or node.text is None:
        return ""
    return node.text.strip()


def parse_package_xml(path: Path) -> tuple[str, set[str]]:
    root = ET.parse(path).getroot()
    name = ""
    deps: set[str] = set()
    for child in list(root):
        tag = _local_tag(child.tag)
        if tag == "name" and not name:
            name = _text(child)
        elif tag in DEPEND_TAGS:
            dep = _text(child)
            if dep:
                deps.add(dep)
    if not name:
        raise RosConsumerError(f"{path}: package.xml has no <name>")
    return name, deps


def find_package_xmls(root: Path) -> list[Path]:
    import os

    root = root.resolve()
    found: list[Path] = []
    for dirpath, dirnames, filenames in os.walk(root):
        current = Path(dirpath)
        dirnames[:] = [
            d for d in dirnames
            if d not in SKIP_DIR_NAMES and not (current / d / "AMENT_IGNORE").exists()
        ]
        if "package.xml" in filenames:
            found.append(current / "package.xml")
    return sorted(found)


def load_catalog(distro: str, catalog_path: Path | None = None) -> dict:
    if catalog_path is None:
        catalog_path = Path(__file__).resolve().parent / "data" / f"{distro}_variants.json"
    if not catalog_path.is_file():
        raise RosConsumerError(
            f"No variant catalog for distro '{distro}' at {catalog_path}"
        )
    return json.loads(catalog_path.read_text(encoding="utf-8"))


def _package_variant(name: str, variants: dict[str, set[str]]) -> str | None:
    for variant in VARIANT_ORDER:
        if name in variants[variant]:
            return variant
    return None


def _max_variant(names: list[str]) -> str:
    rank = {v: i for i, v in enumerate(VARIANT_ORDER)}
    return VARIANT_ORDER[max(rank[n] for n in names)]


@dataclass
class MappingResult:
    workspace: Path
    distro: str
    requires: str
    variant: str
    local_packages: set[str] = field(default_factory=set)
    covered: dict[str, str] = field(default_factory=dict)
    unknown: set[str] = field(default_factory=set)
    package_xmls: list[Path] = field(default_factory=list)

    def format_report(self) -> str:
        lines = [
            f"workspace: {self.workspace}",
            f"package.xml files: {len(self.package_xmls)}",
            f"local packages: {', '.join(sorted(self.local_packages)) or '(none)'}",
            f"ros-kilted deps: {', '.join(f'{n} [{v}]' for n, v in sorted(self.covered.items())) or '(none)'}",
            f"unknown: {', '.join(sorted(self.unknown)) or '(none)'}",
            f"selected variant: {self.variant}",
            f"requires: {self.requires}",
        ]
        return "\n".join(lines)


def map_workspace(
    workspace: Path,
    distro: str = "kilted",
    requires: str | None = None,
    variant: str | None = None,
    catalog: dict | None = None,
) -> MappingResult:
    workspace = workspace.resolve()
    if not workspace.is_dir():
        raise RosConsumerError(f"Workspace path does not exist: {workspace}")

    catalog = catalog or load_catalog(distro)
    catalog_distro = catalog.get("distro", distro)
    conan_version = catalog.get("conan_version")
    if not requires:
        if not conan_version:
            raise RosConsumerError("Catalog is missing conan_version and --requires was not set")
        requires = f"ros-{catalog_distro}/{conan_version}"

    raw_variants = catalog.get("variants") or {}
    variants = {name: set(pkgs) for name, pkgs in raw_variants.items()}
    for name in VARIANT_ORDER:
        if name not in variants:
            raise RosConsumerError(f"Catalog for '{catalog_distro}' is missing variant '{name}'")

    package_xmls = find_package_xmls(workspace)
    if not package_xmls:
        raise RosConsumerError(f"No package.xml found under {workspace}")

    local: dict[str, set[str]] = {}
    for xml_path in package_xmls:
        name, deps = parse_package_xml(xml_path)
        local[name] = deps

    all_deps: set[str] = set()
    for deps in local.values():
        all_deps.update(deps)

    covered: dict[str, str] = {}
    unknown: set[str] = set()
    for dep in sorted(all_deps):
        if dep in local:
            continue
        found = _package_variant(dep, variants)
        if found:
            covered[dep] = found
        else:
            unknown.add(dep)

    if unknown:
        listed = ", ".join(sorted(unknown))
        raise RosConsumerError(
            "These package.xml dependencies are not in ros-kilted "
            f"({catalog_distro} core/base/desktop) and are not local workspace "
            f"packages: {listed}. Creating Conan recipes for extra ROS packages "
            "is not supported yet."
        )

    needed = _max_variant(list(covered.values())) if covered else "core"
    if variant:
        if variant not in VARIANT_ORDER:
            raise RosConsumerError(
                f"Unsupported variant '{variant}'. Use one of: {', '.join(VARIANT_ORDER)}"
            )
        rank = {v: i for i, v in enumerate(VARIANT_ORDER)}
        if rank[variant] < rank[needed]:
            raise RosConsumerError(
                f"Requested variant '{variant}' is smaller than required '{needed}' "
                f"for dependencies: {', '.join(sorted(covered))}"
            )
        selected = variant
    else:
        selected = needed

    return MappingResult(
        workspace=workspace,
        distro=catalog_distro,
        requires=requires,
        variant=selected,
        local_packages=set(local),
        covered=covered,
        unknown=unknown,
        package_xmls=package_xmls,
    )


def render_conanfile_txt(mapping: MappingResult, generators: list[str] | None = None) -> str:
    gens = generators or list(DEFAULT_GENERATORS)
    generators_block = "\n".join(gens)
    return (
        f"{GENERATED_HEADER}\n"
        f"[requires]\n"
        f"{mapping.requires}\n"
        f"\n"
        f"[options]\n"
        f"ros-kilted/*:variant={mapping.variant}\n"
        f"\n"
        f"[generators]\n"
        f"{generators_block}\n"
        f"\n"
        f"[layout]\n"
        f"cmake_layout\n"
    )


def write_conanfile_txt(mapping: MappingResult, output: Path | None = None) -> Path:
    path = output or (mapping.workspace / "conanfile.txt")
    path.write_text(render_conanfile_txt(mapping), encoding="utf-8")
    return path
